version: "2"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - ./gitea-app.ini:/data/gitea/conf/app.ini
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=HayChoToiHaiDiemTua-
      - POSTGRES_DB=gitea
    ports:
      - "5440:5432"
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data