version: "2"

networks:
  gitea:
    external: false

services:
  gitea-server:
    image: gitea/gitea:latest
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - ./gitea-app.ini:/data/gitea/conf/app.ini
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=HayChoToiHaiDiemTua-
      - POSTGRES_DB=gitea
    ports:
      - "5440:5432"
    networks:
      - gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data

  drone-server:
    image: drone/drone:latest
    ports:
      - 8381:8000
      - 9999:9000
    volumes:
      - ./drone-db:/var/lib/drone/    
    restart: always
    networks:
      - gitea
    environment:
      - DRONE_ADMIN=cuong
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server:8381
      - DRONE_SECRET=CSLaMotConLua
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gitea-server:3000/
      - DRONE_NETWORK=gitea
    depends_on:
      - gitea-server

  drone-agent:
    image: drone/agent:0.8
    command: agent
    restart: always
    networks:
      - gitea
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=CSLaMotConLua