version: '3'

volumes:
  gitea-data:
  db:
  drone-db:

networks:
  gitea:
    external: false
 

services:
  gitea-server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=HayChoToiMotDiemTua123-
      - APP_NAME=Techmaster Gitea
      - RUN_MODE=prod
      - FORCE_PRIVATE=true
      - DISABLE_REGISTRATION=false
    ports:
      - 8380:3000
    volumes:
      - gitea-data:/data
      - ./data:/data/gitea
    restart: always
    networks:
      - gitea
    depends_on:
      - gitea-db

  gitea-db:
    image: postgres:alpine
    ports:
      - 5440:5432
    restart: always
    networks:
      - gitea
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=HayChoToiMotDiemTua123-
      - POSTGRES_DB=gitea

  drone-server:
    image: drone/drone:0.8
    ports:
      - 8381:8000
      - 9999:9000
    volumes:
      - drone-db:/var/lib/drone/
    restart: always
    networks:
      - gitea
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server:8381
      - DRONE_SECRET=CSLaMotConLua
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gitea-server:3000/
      - DRONE_NETWORK=gitea
    depends_on:
      - gitea-server

  drone-agent:
    image: drone/agent:0.8
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=CSLaMotConLua